# Generated by Django 5.0.6 on 2024-07-11 07:01

import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.CharField(default="", max_length=50)),
                (
                    "day",
                    models.IntegerField(
                        default=-1, validators=[planning.models.is_valid_day]
                    ),
                ),
                (
                    "start",
                    models.IntegerField(
                        default=-1, validators=[planning.models.is_valid_date]
                    ),
                ),
                (
                    "end",
                    models.IntegerField(
                        default=-1, validators=[planning.models.is_valid_date]
                    ),
                ),
                ("disc", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
